// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA5xAPcrNAAvzfIqy53rUfBF22-uFX5Do',
    appId: '1:510270546540:web:b461d46472c5e89fc2ee49',
    messagingSenderId: '510270546540',
    projectId: 'calorie-tracker-app-506e1',
    authDomain: 'calorie-tracker-app-506e1.firebaseapp.com',
    storageBucket: 'calorie-tracker-app-506e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdghAotXKMtD7c3B5pzZf6kmnpVUZmEy0',
    appId: '1:510270546540:android:36e303ea839c6b83c2ee49',
    messagingSenderId: '510270546540',
    projectId: 'calorie-tracker-app-506e1',
    storageBucket: 'calorie-tracker-app-506e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJRuTinZYmv-d7UxT06lAOK3ZJWFi3RSk',
    appId: '1:510270546540:ios:1b1052107baa8478c2ee49',
    messagingSenderId: '510270546540',
    projectId: 'calorie-tracker-app-506e1',
    storageBucket: 'calorie-tracker-app-506e1.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJRuTinZYmv-d7UxT06lAOK3ZJWFi3RSk',
    appId: '1:510270546540:ios:1b1052107baa8478c2ee49',
    messagingSenderId: '510270546540',
    projectId: 'calorie-tracker-app-506e1',
    storageBucket: 'calorie-tracker-app-506e1.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA5xAPcrNAAvzfIqy53rUfBF22-uFX5Do',
    appId: '1:510270546540:web:2d945f74d54443fcc2ee49',
    messagingSenderId: '510270546540',
    projectId: 'calorie-tracker-app-506e1',
    authDomain: 'calorie-tracker-app-506e1.firebaseapp.com',
    storageBucket: 'calorie-tracker-app-506e1.firebasestorage.app',
  );
}
